#!/bin/bash

# 国内配置
DOMESTIC_GATEWAY="192.168.1.1"
DOMESTIC_DNS="202.96.209.133"

# 海外配置
OVERSEAS_GATEWAY="192.168.1.186"
OVERSEAS_DNS="192.168.1.186"  # 使用Google DNS，可根据需要修改

# 获取默认网络接口
get_default_interface() {
    ip route | grep default | awk '{print $5}' | head -n1
}

# 切换网关
switch_gateway() {
    local gateway=$1
    local interface=$(get_default_interface)
    
    if [ -z "$interface" ]; then
        echo "错误: 无法检测到默认网络接口"
        exit 1
    fi
    
    echo "正在切换网关到: $gateway (接口: $interface)"
    
    # 删除所有现有的默认路由（可能有多个）
    while ip route del default 2>/dev/null; do
        :
    done
    
    # 添加新的默认路由
    if ip route add default via $gateway dev $interface; then
        echo "网关切换成功: $gateway"
    else
        echo "错误: 网关切换失败"
        exit 1
    fi
}

# 切换DNS
switch_dns() {
    local dns=$1
    local interface=$(get_default_interface)
    
    echo "正在切换DNS到: $dns"
    
    # 检查是否使用systemd-resolved
    if systemctl is-active --quiet systemd-resolved 2>/dev/null || systemctl is-enabled --quiet systemd-resolved 2>/dev/null; then
        # 使用resolvectl设置DNS（针对特定接口）
        if resolvectl dns "$interface" "$dns" 2>/dev/null; then
            echo "DNS切换成功: $dns (使用systemd-resolved, 接口: $interface)"
        # 如果接口方式失败，尝试全局设置
        elif resolvectl dns "" "$dns" 2>/dev/null; then
            echo "DNS切换成功: $dns (使用systemd-resolved, 全局设置)"
        else
            echo "错误: DNS切换失败，请检查systemd-resolved服务状态"
            exit 1
        fi
    else
        # 直接修改/etc/resolv.conf（非systemd-resolved系统）
        if [ -w /etc/resolv.conf ]; then
            # 备份原配置
            cp /etc/resolv.conf /etc/resolv.conf.bak.$(date +%Y%m%d_%H%M%S) 2>/dev/null
            
            # 写入新DNS配置
            cat > /etc/resolv.conf <<EOF
# Generated by switch_gateway.sh
nameserver $dns
EOF
            echo "DNS切换成功: $dns (直接修改/etc/resolv.conf)"
        else
            echo "错误: 没有权限修改 /etc/resolv.conf，请使用sudo运行"
            exit 1
        fi
    fi
}

# 显示当前配置
show_current_config() {
    local interface=$(get_default_interface)
    local current_gateway=$(ip route | grep default | awk '{print $3}' | head -n1)
    local current_dns=""
    
    # 优先从systemd-resolved获取DNS
    if systemctl is-active --quiet systemd-resolved 2>/dev/null || systemctl is-enabled --quiet systemd-resolved 2>/dev/null; then
        if [ -n "$interface" ]; then
            current_dns=$(resolvectl dns "$interface" 2>/dev/null | grep -E "DNS Servers:" | awk '{print $3}' | head -n1)
        fi
        # 如果接口方式获取失败，尝试全局获取
        if [ -z "$current_dns" ]; then
            current_dns=$(resolvectl status 2>/dev/null | grep -E "DNS Servers:" | awk '{print $3}' | head -n1)
        fi
    fi
    
    # 如果systemd-resolved获取失败，从/etc/resolv.conf读取（作为备用）
    if [ -z "$current_dns" ]; then
        current_dns=$(grep nameserver /etc/resolv.conf 2>/dev/null | awk '{print $2}' | head -n1)
    fi
    
    echo "当前配置:"
    echo "  网络接口: $interface"
    echo "  网关: ${current_gateway:-未设置}"
    echo "  DNS: ${current_dns:-未设置}"
}

# 主函数
main() {
    if [ $# -eq 0 ]; then
        echo "用法: $0 [国内|海外|domestic|overseas]"
        echo ""
        echo "参数说明:"
        echo "  国内/domestic  - 切换到国内配置"
        echo "  海外/overseas - 切换到海外配置"
        echo ""
        show_current_config
        exit 1
    fi
    
    local mode=$1
    
    case "$mode" in
        国内|domestic|cn|CN)
            echo "切换到国内配置..."
            switch_gateway "$DOMESTIC_GATEWAY"
            switch_dns "$DOMESTIC_DNS"
            echo ""
            show_current_config
            ;;
        海外|overseas|en|EN)
            echo "切换到海外配置..."
            switch_gateway "$OVERSEAS_GATEWAY"
            switch_dns "$OVERSEAS_DNS"
            echo ""
            show_current_config
            ;;
        *)
            echo "错误: 无效的参数 '$mode'"
            echo "用法: $0 [国内|海外|domestic|overseas]"
            exit 1
            ;;
    esac
}

# 检查是否以root权限运行
if [ "$EUID" -ne 0 ]; then
    echo "警告: 此脚本需要root权限来修改网络配置"
    echo "请使用 sudo 运行: sudo $0 $@"
    exit 1
fi

main "$@"

